<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Bun3.Server.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="[13.0.2]" />
    <PackageReference Include="NUnit" Version="4.1.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Tools" Version="2.68.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\game.proto" GrpcServices="None" />
    <Protobuf Include="Protos\players_game.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bun3.Server.Auth\Bun3.Server.Auth.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Auth.Steam\Bun3.Server.Auth.Steam.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Abstractions\Bun3.Server.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Core\Bun3.Server.Core.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Transport.Tcp\Bun3.Server.Transport.Tcp.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Hosting\Bun3.Server.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Rpc\Bun3.Server.Rpc.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Players\Bun3.Server.Players.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Ticking\Bun3.Server.Ticking.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.GameplayTags\Bun3.Server.GameplayTags.csproj" />
    <ProjectReference Include="..\..\src\Bun3.Server.Items\Bun3.Server.Items.csproj" />
    <ProjectReference Include="..\..\..\common\src\com.bun3.gameplay\Catalog\Bun3.Gameplay.Catalog.csproj" />
  </ItemGroup>

</Project>
